[package]
name = "tackc_ast"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"] }
tackc_global.workspace = true
tackc_lexer.workspace = true
tackc_span.workspace = true
thin-vec = { workspace = true, features = ["serde"] }

[lints]
workspace = true
