[package]
name = "tackc_span"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, features = ["derive"], optional = true }

[lints]
workspace = true

[features]
serde = ["dep:serde"]
