[package]
name = "tackc_span"
version = "0.1.0"
edition = "2024"

[dependencies]
proptest = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true

[features]
