[package]
name = "tackc_span"
version = "0.1.0"
edition = "2024"

[dependencies]
proptest = "1.9.0"
proptest-derive = "0.7.0"
serde = { workspace = true, features = ["derive"], optional = true }

[lints]
workspace = true

[features]
serde = ["dep:serde"]
