[package]
name = "tackc_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
rand.workspace = true
tackc_macros_impl = { version = "0.1.0", path = "../tackc_macros_impl" }

[lints]
workspace = true
