[package]
name = "tackc_file"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true, optional = true }
tackc_macros = { version = "0.1.0", path = "../tackc_macros" }

[lints]
workspace = true

[features]
serde = ["dep:serde"]
