[package]
name = "tackc_file"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tackc_hash = { workspace = true }
tackc_span = { workspace = true }

[lints]
workspace = true
