[alias]
tackc = "run -p tackc --bin tackc --"
tackc-release = "run -p tackc --bin tackc --release --"
hash = "run -p tackc_meta --bin hash --quiet"
verify = "run -p tackc_meta --bin verify --release --quiet --"
