[package]
name = "tackc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
tackc_error = { workspace = true }
tackc_file = { workspace = true }
tackc_global = { workspace = true }
tackc_lexer = { workspace = true }
